name: tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=dlgv24_php-project-9
            -Dsonar.organization=dlgv24
            -Dsonar.sources=src/
            -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
